### ISSUE TITLE
[API] GET Request contains body

### ISSUE THREAD

**Issue by MADITT** [skaupper/VirtualJukebox#25]
After trying to implement GET request as statet, I figured out, that the frameworks are not capable of dealing with a body when a GET request is carried out. Two different frameworks (okhttp and volley) were used but the they got the same behaviour. The Desktop Team did not try a GET request with a body yet. 

I will try to research a bit to solve this issue otherwise I would recommend changing the given REST interface. 
Suggestion: Moving the session_id to the url. (This would solve the problem for "Get current queues".) All gets which rely on more parameters than the session_id may be converted to PUT or POST requests. (e.g.: "Generating a session" to POST; "Querying tracks" to PUT)

**Comment by skaupper** [comment]
@MADITT  you may want to see the latest commit of #16 and approve the PR if you are satisfied with the solution.

I will close the issue myself as soon as the PR is merged.

**Comment by MADITT** [comment]
Putting the GET body into the url as parameters looks quite nice to me. 
From my point of view you can close the issue.
