### ISSUE TITLE
It should be possible that nothing is currently played

### ISSUE THREAD

**Issue by skaupper** [skaupper/VirtualJukebox#49]
Since the server starts without anything added to any queue it should be possible that the current playback is empty.

**Comment by wurmmi** [comment]
This somehow links into my current PR #50.
However, I guess this will take some major modifications to RAMDataStrore and SpotifyAPI.
Thus, I would like to implement this issue in a separate PR.

**Comment by skaupper** [comment]
This issue also includes the following scenarios:
- Skipping when both queues are empty
- The `PlayerAction` `Play` should schedule a track if none has been played so far (not just sending a play request)

**Comment by wurmmi** [comment]
this was fixed with #58 .

we should test it before we close the issue.

**Comment by skaupper** [comment]
i think the datastore (or at least the jukebox) need support for this too

**Comment by skaupper** [comment]
after i looked through the code it seems fine to me. all that remains are some inconsistency checks which are part of #59
