### ISSUE TITLE
Undetected spotify device

### ISSUE THREAD

**Issue by skaupper** [skaupper/VirtualJukebox#51]
If the spotify player hasn't been started manually, the web API cannot find the device. How should we handle that?

**Comment by wurmmi** [comment]
We could gracefully exit the entire server program with an error message?

**Comment by skaupper** [comment]
Probably yes. In order to do so we may need to delay the start of the main webserver after we successfully got a valid access token, so we can handle this error before we actually start the server.

However, this may be worth a separate PR.

**Comment by janeson332** [comment]
Wouldn't it be better if we notify the client that there is no available playback?

**Comment by skaupper** [comment]
Generate `SpotifyNoDevice` error, if no device is available.
#58

**Comment by janeson332** [comment]
should be fixed with setting a playback to a device
if no device is available SpotifyNoDevice Error gets returned

**Comment by janeson332** [comment]
fixed when a spotifyDevice is set in the config file, otherwise not..

**Comment by skaupper** [comment]
seems fine :+1: 
i guess we cant get a better solution (due to limitations by spotify)
