### ISSUE TITLE
`currentVote` is always true

### ISSUE THREAD

**Issue by skaupper** [skaupper/VirtualJukebox#53]
When adding tracks to a queue the field `currentVote` is not set and therefore always has the default value (`true`).

Furthermore, the REST endpoint `getCurrentQueues` must set the values of `currentVote` according to the user who requested the queue.

**Comment by wurmmi** [comment]
not clear to me what the issue is here.

several objects in `addTrackToQueue()` and `getCurrentQueue()` are instances of `PlaybackTrack`, which don't have the field `currentVote`....?

**Comment by skaupper** [comment]
the field `currentVote` of the tracks in the normal queue should indicate if the user has already voted for a track.
these fields should be set in `getCurrentQueues`. whether it is done in the DataStore or in the JukeBox doesnt make that much of a difference

**Comment by skaupper** [comment]
a call to `getCurrentQueues` with 3 newly added tracks responds with the following JSON body:

```js
{
  "admin_queue": [],
  "currently_playing": {},
  "normal_queue": [
    {
      "added_by": "",
      "album": "Whoopsy Daisy",
      "artist": "Wolfgang Lohr & Balduin & Sebastian Daws & ",
      "current_vote": 1,
      "duration": 273987,
      "icon_uri": "https://i.scdn.co/image/ab67616d0000b273bc9fc92373ef9bc8f9d8cd4b",
      "title": "Whoopsy Daisy (Club Mix)",
      "track_id": "spotify:track:6oomEes8hP95cWb8S898xF",
      "votes": 0
    },
    {
      "added_by": "",
      "album": "Princes of Egypt",
      "artist": "Caleb Hyles & Jonathan Young & ",
      "current_vote": 1,
      "duration": 262813,
      "icon_uri": "https://i.scdn.co/image/ab67616d0000b2731019a7af1080acd741a6228b",
      "title": "Deliver Us",
      "track_id": "spotify:track:0aZIlnIkxIO8siYRV5SIkN",
      "votes": 0
    },
    {
      "added_by": "",
      "album": "Scream Aim Fire Deluxe Edition",
      "artist": "Bullet For My Valentine & ",
      "current_vote": 1,
      "duration": 247693,
      "icon_uri": "https://i.scdn.co/image/ab67616d0000b2736b997d8f2a6ea90813d6e67e",
      "title": "Waking the Demon",
      "track_id": "spotify:track:2ZCCkqminNZiitXgbFArXM",
      "votes": 0
    }
  ]
}
```

you can see that `current_vote` is already `1` for every track (which is wrong) but `votes` is still `0` (which is right)

I just pushed a script to #63 which illustrates that behvaiour. you may want to have a look at it. You would need Spotify for that though
