### ISSUE TITLE
Inconsistency between Spotify and DataStore on server start

### ISSUE THREAD

**Issue by wurmmi** [skaupper/VirtualJukebox#59]
The usual startup process for the VirtualJukebox project is:
- start server (all queues empty)
- start spotity player device 
- press play on spotify player device (Play a random song. This is to make it available as an "Active device" for the API) 
- start client

Client polls `getCurrentQueues`. Since Spotify is already playing a song, the consistency check will always fail here at the first time.

Resolve:
---OPTION 1
- remove the consistency check entirely (It's not a usecase anyway. Spotify and DataStore can never go out of sync, since a user should never touch his playback device to skip songs manually from there)
- on very first `addTrackToQueue` set the currentPlayback in Spotify `mMusicBackend->setPlayback`

---OPTION 2
- on very first `addTrackToQueue` set the currentPlayback in Spotify `mMusicBackend->setPlayback`
- start checking consistency after first track was added. Return an error to the user like "You should not touch the playback device - don't modify the playback there!!"

**Comment by skaupper** [comment]
> on very first `addTrackToQueue` set the currentPlayback in Spotify `mMusicBackend->setPlayback`

this is needed in any case. i do think returning an everytime `getCurrentQueues` is called will become annoying very fast, so maybe a debug log (with `VLOG(...)`) would be a good compromise

**Comment by janeson332** [comment]
This problem should be fixed with the SimpleScheduler implementation (#67), but there are still some sporadically incosistency errors when the next song starts playing

**Comment by wurmmi** [comment]
This was fixed with #67. Verified through testing.

Remaining minimal issues when manually modifying the playing track on the playback device.
Closing anyway, since the playback device shouldn't be touched while playing. It's not a use case.
