### ISSUE TITLE
Calls to the SpotifyAPI behave differently depending on the device used

### ISSUE THREAD

**Issue by skaupper** [skaupper/VirtualJukebox#60]
Multiple calls to `play` or `pause` may produce `Restriction violated` errors if the player is already playing/paused.

Additionally all calls to the SpotifyAPI should be threadsafe

**Comment by skaupper** [comment]
#58

**Comment by janeson332** [comment]
should be fixed
needs to be tested from someone else, because i havn't got these errors

**Comment by skaupper** [comment]
seems to work now  :+1:
