### ISSUE TITLE
queryTracks returns null 

### ISSUE THREAD

**Issue by MADITT** [skaupper/VirtualJukebox#62]
When I make a queryTracks request with the parameter pattern=Whoopsy I obtain a list of tracks back from the server (Also one Track called Whoopsy Daisy). When I make a queryTracks with the parameter pattern=Wjoopsy D I obtain "{"tracks":null}" as response from the server. 

Following the url for the second query: http://193.170.132.206:8888/api/v1/queryTracks?pattern=Whoopsy%20D&session_id=ID41576253660&max_entries=10

**Comment by janeson332** [comment]
did you use the latest master branch? just checked with wireshark and got a response with an empty vector : 
`{"tracks":[]}`

**Comment by skaupper** [comment]
actually an empty vector is not the expected result either, since there has to be entries
the fact that it returns `null` instead of an empty array is due to an old version.

i just tested myself and it returns indeed no results

**Comment by skaupper** [comment]
currently we are encoding spaces as `%20` when calling the search endpoint of spotify (which should be legit according to the Web API docs).

if i change `%20` to `&20` it seems to work. @janeson332  do you want to look into that or should we just change it?

**Comment by skaupper** [comment]
hmm, when using `&20` the part after the space seems to be ignored
it seems like the API is broken because when i test the same query using the Spotify Developer console it doesnt work either.

so i guess this issue is _wont fix_ because we cant do anything against it
